apiVersion: v1
kind: Pod
metadata:
  name: netshoot-with-sa 
  labels:
    name: netshoot-with-sa 
spec:
  serviceAccount: default
  containers:
  - name: netshoot-with-sa 
    image: nicolaka/netshoot
    command:
      - "/bin/bash"
    args:
      - "-c"
      - "while true;do sleep 2; echo sleep; done"
    resources:
      limits:
        memory: "128Mi"
        cpu: "0.1"
